CREATE TABLE LOGIN(
	  
	  USER_NAME VARCHAR(300) NOT NULL,
	  PASSWORD TEXT NOT NULL,
	  HINT_QUESTION VARCHAR(200) NOT NULL,
	  HINT_ANSWER VARCHAR(200) NOT NULL,
	  USER_TYPE VARCHAR(200) NOT NULL
	  
);

CREATE TABLE ADMIN(

         A_ID VARCHAR(37) NOT NULL,
	 A_NAME VARCHAR(255) NOT NULL,
	 A_PASSWORD TEXT NOT NULL,
	 A_EMAIL VARCHAR(400) UNIQUE NOT NULL,
	 A_GENDER VARCHAR(200) NOT NULL,
	 A_MOBILE_NO VARCHAR(100) NOT NULL,
	 PRIMARY KEY (A_ID)
	);
